"""initial schema

Revision ID: bf444492feff
Revises: 
Create Date: 2026-05-16 06:06:12.043139

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'bf444492feff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('uyu_per_usd', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', name='uq_fx_rate_date_source')
    )
    op.create_table('studio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('default_lang', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'email', name='uq_user_studio_email')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('jornal_uyu', sa.Float(), nullable=False),
    sa.Column('viatico_uyu', sa.Float(), nullable=False),
    sa.Column('auc_pct', sa.Float(), nullable=False),
    sa.Column('j_per_m2_casa', sa.Float(), nullable=False),
    sa.Column('j_per_m2_deck', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'code', name='uq_rubro_studio_code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('casa_m2', sa.Float(), nullable=False),
    sa.Column('deck_m2', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['budget_version.id'], name='fk_budget_current_ver', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('labor_param_id', sa.Integer(), nullable=True),
    sa.Column('fx_rate_uyu_usd', sa.Float(), nullable=False),
    sa.Column('contingency_pct', sa.Float(), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['labor_param_id'], ['labor_param.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_version_id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_price_usd_snapshot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_version.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_version_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_version_id', sa.Integer(), nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=True),
    sa.Column('author_kind', sa.String(length=10), nullable=False),
    sa.Column('author_ref', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_version.id'], ),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('share_token')
    op.drop_table('line_item')
    op.drop_table('budget')
    op.drop_table('budget_version')
    op.drop_table('project')
    op.drop_table('material')
    op.drop_table('audit_log')
    op.drop_table('rubro')
    op.drop_table('labor_param')
    op.drop_table('client')
    op.drop_table('app_user')
    op.drop_table('studio')
    op.drop_table('fx_rate')
    # ### end Alembic commands ###
