"""Add studio_id to budget tables, unique constraint to material

Revision ID: 20260516_add_studio_id
Revises: bf444492feff
Create Date: 2026-05-16 08:40:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '20260516_add_studio_id'
down_revision = 'bf444492feff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add studio_id to budget
    op.add_column('budget', sa.Column('studio_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_budget_studio_id', 'budget', 'studio', ['studio_id'], ['id'])
    op.alter_column('budget', 'studio_id', server_default=None)
    
    # Add studio_id to budget_version
    op.add_column('budget_version', sa.Column('studio_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_budget_version_studio_id', 'budget_version', 'studio', ['studio_id'], ['id'])
    op.alter_column('budget_version', 'studio_id', server_default=None)
    
    # Add studio_id to line_item
    op.add_column('line_item', sa.Column('studio_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_line_item_studio_id', 'line_item', 'studio', ['studio_id'], ['id'])
    op.alter_column('line_item', 'studio_id', server_default=None)
    
    # Add studio_id to comment
    op.add_column('comment', sa.Column('studio_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_comment_studio_id', 'comment', 'studio', ['studio_id'], ['id'])
    op.alter_column('comment', 'studio_id', server_default=None)
    
    # Add studio_id to share_token
    op.add_column('share_token', sa.Column('studio_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_share_token_studio_id', 'share_token', 'studio', ['studio_id'], ['id'])
    op.alter_column('share_token', 'studio_id', server_default=None)
    
    # Add unique constraint to material
    op.create_unique_constraint('uq_material_rubro_code', 'material', ['rubro_id', 'code'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop unique constraint from material
    op.drop_constraint('uq_material_rubro_code', 'material', type_='unique')
    
    # Drop studio_id from share_token
    op.drop_constraint('fk_share_token_studio_id', 'share_token', type_='foreignkey')
    op.drop_column('share_token', 'studio_id')
    
    # Drop studio_id from comment
    op.drop_constraint('fk_comment_studio_id', 'comment', type_='foreignkey')
    op.drop_column('comment', 'studio_id')
    
    # Drop studio_id from line_item
    op.drop_constraint('fk_line_item_studio_id', 'line_item', type_='foreignkey')
    op.drop_column('line_item', 'studio_id')
    
    # Drop studio_id from budget_version
    op.drop_constraint('fk_budget_version_studio_id', 'budget_version', type_='foreignkey')
    op.drop_column('budget_version', 'studio_id')
    
    # Drop studio_id from budget (must drop FK first)
    op.drop_constraint('fk_budget_current_ver', 'budget', type_='foreignkey')
    op.drop_constraint('fk_budget_studio_id', 'budget', type_='foreignkey')
    op.drop_column('budget', 'studio_id')
    op.create_foreign_key('fk_budget_current_ver', 'budget', 'budget_version', ['current_version_id'], ['id'], use_alter=True)
    
    # ### end Alembic commands ###
